name: Go package

on: [push]

jobs:
  build:

    runs-on: [self-hosted, windows, x64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up vm
        uses: actions/checkout@v3
      - name: lol
        run: ssh
        
